export default {
  login: "abc",
  id: 730366551,
  node_id: "MDQ6VXNlcjczMDI2NjQx",
  avatar_url: "https://avatars.githubusercontent.com/u/73026641?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/akash26khanra",
  html_url: "https://github.com",
  followers_url: "https://api.github.com/users/akash26khanra/followers",
  following_url:
    "https://api.github.com/users/akash26khanra/following{/other_user}",
  gists_url: "https://api.github.com/users/akash26khanra/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/akash26khanra/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/akash26khanra/subscriptions",
  organizations_url: "https://api.github.com/users/orgs",
  repos_url: "https://api.github.com/users/repos",
  events_url: "https://api.github.com/users/events{/privacy}",
  received_events_url: "https://api.github.com/users/received_events",
  type: "User",
  site_admin: false,
  name: "Dummy",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 50,
  public_gists: 2,
  followers: 1000,
  following: 1000,
  created_at: "2020-10-17T13:31:31Z",
  updated_at: "2023-08-19T14:02:18Z",
};
